name: Create Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
            
      - name: Build binaries for multiple platforms
        run: |
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o r2d2-linux-amd64 .
          tar -czvf r2d2-linux-amd64.tar.gz r2d2
          
          # Build for macOS (both Intel and Apple Silicon)
          GOOS=darwin GOARCH=amd64 go build -o r2d2-darwin-amd64 .
          tar -czvf r2d2-darwin-amd64.tar.gz r2d2
          
          GOOS=darwin GOARCH=arm64 go build -o r2d2-darwin-arm64 .
          tar -czvf r2d2-darwin-arm64.tar.gz r2d2
          
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o r2d2-windows-amd64.exe .
          zip r2d2-windows-amd64.zip r2d2.exe
      
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            r2d2-linux-amd64.tar.gz
            r2d2-darwin-amd64.tar.gz
            r2d2-darwin-arm64.tar.gz
            r2d2-windows-amd64.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
