name: Create Release
on:
  push:
    tags:
      - 'v*'  # Triggers when a tag starting with "v" is pushed
permissions:
  contents: write
  releases: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Current stable version as of April 2025
      
      - name: Build binary
        run: |
          go build -o r2d2 .
          tar -czvf r2d2.tar.gz r2d2
      
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: r2d2.tar.gz
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
